### PR TITLE
Add arm-gcc-xpack formula

### PR DESCRIPTION
**Pull request by rleh**
... and Github Actions CI pipeline to test it.

### CODE REVIEW

**Comment by rleh** [comment]
@salkinium Could you please check if it works on your Mac?

**Review by salkinium — APPROVED** [review]
Works as advertised! (on ARM64 macOS, and the CI tests x86)

**Comment by salkinium** [comment]
It appears I spoke too soon, the Python3 openssl certificate somehow gets put into the Python3 installation.
This breaks any urllib.request (that I need for scraping ST's data ;-). Completely unclear why that happens, but it's pretty bad. Perhaps it's just on my machine… I'll investigate later in the week.

```
 $ python3 -c 'import ssl; print(ssl.get_default_verify_paths().openssl_cafile)'
/Users/ilg/actions-runners/xpack-dev-tools/_work/arm-none-eabi-gcc-xpack/arm-none-eabi-gcc-xpack/build/darwin-arm64/aarch64-apple-darwin20.6.0/install/openssl/cert.pem

 $ brew uninstall arm-gcc-xpack@12
Uninstalling /opt/homebrew/Cellar/arm-gcc-xpack@12/12.2.Rel1... (6,499 files, 815.6MB)

 $ python3 -c 'import ssl; print(ssl.get_default_verify_paths().openssl_cafile)'
/opt/homebrew/etc/openssl@1.1/cert.pem
```

**Comment by rleh** [comment]
Where does this `build/` subdirectory come from? There is no such directory in the xpack archive and there is also no `cert.pem` in the xpack archive (but there are some cert/.pem files in the archive in `xpack-arm-none-eabi-gcc-12.2.1-1.2/lib/python3.11/test/`).

The xPack manual installation guide [warns against putting the toolchain path to the user or system path](https://xpack.github.io/dev-tools/arm-none-eabi-gcc/install/#test-1), maybe that is the problem?
Is there an alternative way in MacOS to using $PATH?

**Comment by salkinium** [comment]
The build path comes from the build machine that was used to build the toolchain. It's hard coded in quite a lot of places (grep for it).

I think it's some weird interaction with my local Python 3.11 installation and theirs, probably Homebrew is running something during installation that it shouldn't. I'll investigate further.

**Pull request merged**
